version: '3'
services:
  app:
    container_name: express
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
    